### ISSUE TITLE
Lighthouse audits not working, 

### ISSUE THREAD

**Issue by bikker** [StanGirard/seo-audits-toolkit#12] opened 2020-07-23 15:51 UTC
Lighthouse audits not working, i tested both in docker and normal installation it just wont save the url when we submit the url. Google api is added to env

**Comment by StanGirard** [comment] 2020-07-23 20:44
Could you please provide some logs? 
What is the URL you tried?

**Comment by StanGirard** [comment] 2020-07-23 22:21
Please try [the new release](https://github.com/StanGirard/seo-audits-toolkit/releases/tag/V1.3) and let me know if the issue is still here.

Please note that you need to install Redis for this new version to work.

**Comment by StanGirard** [comment] 2020-07-26 17:19
Closing issue. If the problem still exists please reopen it

**Comment by bikker** [comment] 2020-08-07 18:24
just did a fresh new install same issue ,this is my env file 
SQLALCHEMY_DATABASE_URI=sqlite:///database.db
GOOGLE_API_KEYS= MY KEY ADDED HERE

and installed redis-server and its up , installed as per requirements using pip3

http://lh.scalingweb.com/  < u can test here its live here

**Comment by StanGirard** [comment] 2020-08-07 18:28
Hello, what are the logs of the celery worker ? 

Have you started it with: `celery worker -A celery_worker.celery --loglevel=info` ?

**Comment by bikker** [comment] 2020-08-07 18:37
yes i did, whats the defualt path for log file for celery in ubuntu?

**Comment by StanGirard** [comment] 2020-08-07 18:44
Well you need to keep the script running.

In order to run the SEO toolkit you need to open three terminals. In each run:
- `python3 run.py`
- `redis-server`
- `celery worker -A celery_worker.celery --loglevel=info`

And keep the scripts running.

**Comment by StanGirard** [comment] 2020-08-07 18:45
After looking at your website. It seems that none of the tools are working. It is probably because the celery worker is not running.

**Comment by bikker** [comment] 2020-08-07 18:49
[2020-08-07 20:49:07,257: ERROR/ForkPoolWorker-3] Task Lighthouse[cfbb104e-07d0-4d0a-bffe-a9ee1be7ac29] raised unexpected: KeyError('lighthouseResult',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/SEOToolkit/toolkit/celery_utils.py", line 7, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/SEOToolkit/toolkit/celeryapp/tasks.py", line 35, in LighthouseAudit
    accessibility = int(math.floor(value["lighthouseResult"]["categories"]["accessibility"]["score"] * 100))
KeyError: 'lighthouseResult'

**Comment by StanGirard** [comment] 2020-08-07 18:55
After trying with my own project. It seems like you have an error with your google apikey

**Comment by bikker** [comment] 2020-08-07 19:11
Thank you ! its working now ! , last question how can i secure this with a login ?

**Comment by StanGirard** [comment] 2020-08-07 19:19
You are welcome ! 

Well there aren't any login option right now but you can implement an Http basic authentication on the nginx/apache side: 
https://developer.mozilla.org/docs/Web/HTTP/Authentication

**Closed by StanGirard** 2020-08-07 19:19 UTC

**Comment by bikker** [comment] 2020-08-07 19:48
where can i switch the lighthouse to change the scores from desktop to mobile !

**Comment by StanGirard** [comment] 2020-08-07 19:51
I have not yet implemented it. There is going to be a big update in a month or so that should add many features

**Comment by bikker** [comment] 2020-08-07 19:54
i understand that but 
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fintodns.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo

like this url fetches the json for lighthouse  if u change strategy=mobile or strtegy=desktop that gives those , in which file have you added the url in the code which i can go edit, i looked and didnt find in any yet

**Comment by StanGirard** [comment] 2020-08-07 20:07
You can find the request generated in this file: 

https://www.github.com/StanGirard/seo-audits-toolkit/tree/master/toolkit%2Fcontroller%2Fseo%2Flighthouse.py

**Comment by bikker** [comment] 2020-08-07 20:07
THANK YOU !

**Comment by StanGirard** [comment] 2020-08-07 20:11
Please bare with me. I'm doing this as a side project and I don't have a lot of free time. New functionalities should be arriving each month. 

End goal is to build a free toolkit to audit websites in depth.

**Comment by StanGirard** [comment] 2020-08-07 20:12
And feel free to give me any feedback or even make some pull requests :)

**Comment by bikker** [comment] 2020-08-07 20:12
sure ! will help as much as i can by testing ! :) thank you
